SELECT * FROM emp;

SELECT * FROM DEPT;

-- AS 별칭 => ""
SELECT DNAME AS "부서 이름" FROM DEPT WHERE DEPTNO=20; -- WHERE 절은 조건

SELECT DNAME AS "부서 이름" FROM DEPT WHERE DEPTNO>=30; -- WHERE 절은 조건

-- order by 는 항상 맨 뒤에 작성 : 조회 후 정렬
SELECT ENAME, SAL FROM EMP WHERE SAL>= 1000 AND SAL <=2000 ORDER BY SAL DESC;

SELECT * FROM EMP WHERE ENAME='ALLEN';

UPDATE EMP SET SAL=2000 WHERE EMPNO=7499;

SELECT ENAME, SAL FROM EMP WHERE SAL>= 1000 AND 1999.99 ORDER BY SAL DESC;

SELECT ENAME, SAL FROM EMP WHERE SAL BETWEEN 1000 AND 2000;

--TU???
SELECT * FROM EMP WHERE ENAME='TU'; -- 완전히 같은 사람을 찾는 것
SELECT * FROM EMP WHERE ENAME like 'TU%';
SELECT * FROM EMP WHERE ENAME like '%NE%';
SELECT * FROM EMP WHERE ENAME like '__RD';

-- 거의 대부분의 DB는 날짜를 문자열로 조회 가능 (자동파싱 "13"=>13, "{a:10}"=>{a:10})
SELECT ENAME, HIREDATE FROM EMP WHERE HIREDATE>'1981-09-01';
SELECT ENAME, HIREDATE FROM EMP WHERE HIREDATE='1987-07-13';
SELECT ENAME, HIREDATE FROM EMP WHERE HIREDATE='1987-7-13';
SELECT ENAME, HIREDATE FROM EMP WHERE HIREDATE>='1981-09-01' AND HIREDATE<'1981-10-01';
-- SELECT ENAME, HIREDATE FROM EMP WHERE HIREDATE='1987-09';
-- oracle은 지원하지 않음
-- BETWEEN A AND B (A부터 B까지 둘 다 포함) : 수
-- BETWEEN DATE A AND DATE B (A부터 B까지 둘 다 포함) : 수
SELECT ENAME, HIREDATE FROM EMP WHERE HIREDATE BETWEEN '1981-09-01' AND '1981-09-30';

-- 1. EMP 테이블에서 모든 사원의 정보를 조회
SELECT ENAME FROM EMP; -- V

-- 2. EMP 테이블에서 사원 이름(ENAME)과 급여(SAL)만 조회
SELECT ENAME,SAL FROM EMP; -- V

-- 3. EMP 테이블에서 부서 번호(DEPTNO)가 10인 사원의 이름과 직무를 조회
SELECT ENAME, JOB FROM EMP WHERE DEPTNO=10; -- V

-- 4. EMP 테이블에서 급여가 2000이상인 사원의 이름과 급여를 조회
SELECT ENAME, SAL FROM EMP WHERE SAL>=2000; -- V

-- 5. EMP 테이블에서 직무(JOB)가 'CLERK'인 사원의 모든 정보를 조회하시오
SELECT * FROM EMP WHERE JOB='CLERK'; -- V

-- 6. EMP 테이블에서 이름이 'S'로 시작하는 사원의 이름과 부서 번호를 조회하시오 (LIKE 'S%')
SELECT ENAME, DEPTNO FROM EMP WHERE ENAME LIKE 'S%'; -- V

-- 7. EMP 테이블에서 이름이 'T'로 끝나는 사원의 이름과 직무를 조회하시오 (LIKE '%T')
SELECT ENAME, JOB FROM EMP WHERE ENAME LIKE '%T'; -- V

-- 8. EMP 테이블에서 커미션 (COMM)이 NULL인 사원의 이름과 급여를 조회하시오 (IS NULL)
SELECT ENAME, SAL FROM EMP WHERE COMM IS NULL; -- V

-- 9. EMP 테이블에서 매니저(MGR)가 없는 사원의 이름과 직무를 조회하시오 (MGR IS NULL)
SELECT ENAME, JOB FROM EMP WHERE MGR IS NULL; -- V

-- 10. EMP 테이블에서 급여(SAL)가 1500이상 3000 이하인 사원의 이름과 급여를 조회하시오 (BETWEEN)
SELECT ENAME, SAL FROM EMP WHERE SAL BETWEEN 1500 AND 3000; -- V

-- 11. EMP 테이블에서 1981년에 입사한(HIREDATE) 사원의 이름과 입사일을 조회하시오. (연도 조건)
SELECT ENAME, HIREDATE FROM EMP WHERE HIREDATE BETWEEN DATE'1981-01-01' AND DATE '1981-12-13'; -- V

-- 12. DEPT 테이블에서 모든 부서의 이름(DNAME)과 지역(LOC)을 조회하시오
SELECT DNAME, LOC FROM DEPT; -- V

-- 13. EMP 테이블에서 부서 번호가 20번 또는 30번인 사원의 이름과 부서 번호를 조회하시오 (IN (20,30))
SELECT ENAME,DEPTNO FROM EMP WHERE DEPTNO IN(20,30); -- V

-- 14. EMP 테이블에서 보너스(COMM)가 0보다 큰 사원의 이름, 급여, 보너스를 조회하시오 (COMM >0)
SELECT ENAME, SAL, COMM FROM EMP WHERE COMM>0; -- V

-- 15. EMP 테이블에서 직무(JOB)가 'MANAGER'인 사원의 이름, 부서 번호, 입사일을 조회하시오
SELECT ENAME, DEPTNO, HIREDATE FROM EMP WHERE JOB='MANAGER'; -- V



-- ****************
-- 형변환 SQL문제 (5)
-- 1. EMP테이블에서 모든 사원의 입사일(HIREDATE)을 YYYY-MM-DD 형식의 문자열로 변환하여 조회하시오.
--SELECT TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') FROM DUAL;
SELECT TO_CHAR(SYSDATE, 'YYYY-MM-DD' ) FROM EMP ;

-- 2. 문자열 '2025-01-15'를 DATE형식으로 변환하여 조회하시오.
SELECT TO_DATE('2025-01-15', 'YYYY-MM-DD')FROM DUAL;

-- 3. EMP 테이블에서 급여(SAL)를 통화 형식(9,999) 문자열로 변환하여 조회하시오.
SELECT TO_CHAR(sal,'L9,999')   FROM EMP;

-- 4. 문자열 '1,2,34'를 숫자로 변환한 후 10을 더한 결과를 조회하시오.
SELECT TO_NUMBER('1,2,34','9999')+10 AS RESULT FROM DUAL;
SELECT TO_NUMBER('1','9999')+10 AS RESULT FROM DUAL;
SELECT TO_NUMBER('2','9999')+10 AS RESULT FROM DUAL;
SELECT TO_NUMBER('34','9999')+10 AS RESULT FROM DUAL;

-- 5. EMP 테이블에서 급여(SAL)를 VARCHAR2로 캐스팅하여 문자열로 조회하시오.
-- SELECT TO_CHAR(SAL, '9999') AS SAL FROM EMP;
SELECT CAST(SAL AS VARCHAR2(10)) AS SAL_STR FROM EMP;





