-- SELECT * FROM EMP WHERE COMM = NULL;
-- null 은 없는 데이터기 때문에 동등비교연산 불가
SELECT * FROM EMP WHERE COMM IS NULL; -- 커미션을 받지 않는 사람
SELECT * FROM EMP WHERE COMM IS NOT NULL; -- 커미션을 받는 사람

-- 부서 20 이거나(또는) 30인 사원
SELECT * FROM EMP WHERE DEPTNO=20 OR DEPTNO=30;
SELECT * FROM EMP WHERE DEPTNO IN (20,30);
SELECT * FROM EMP WHERE DEPTNO NOT IN (20,30);

