SELECT * FROM EMP WHERE SAL>=2000;

-- VIEW 생성하기
CREATE VIEW EMP_2000_SAL AS SELECT * FROM EMP WHERE SAL>=2000;

SELECT * FROM EMP_2000_SAL;

SELECT EMP.*, DEPT.DNAME, DEPT.LOC
FROM EMP LEFT OUTER JOIN DEPT
    ON EMP.DEPTNO=DEPT.DEPTNO;

-- VIEW 생성하기
CREATE VIEW EMP_DEPT AS
    SELECT EMP.*, DEPT.DNAME, DEPT.LOC
    FROM EMP LEFT OUTER JOIN DEPT
         ON EMP.DEPTNO=DEPT.DEPTNO;

SELECT * FROM EMP_DEPT;

-- VIEW 삭제하기
DROP VIEW EMP_2000_SAL CASCADE CONSTRAINTS ;

SELECT * FROM EMP_2000_SAL; -- 더이상 존재하지 않음


SELECT * FROM EMP_DEPT;

-- CREATE DDL

DROP VIEW EMP_2000_SAL;
-- GRANT REVOTE DCL
-- SELECT (DQL),I,D,U DML
-- JDB


-- **************************************** VIEW 문제풀이 ****************************************--
SELECT * FROM EMP;


-- CREATE VIEW { 뷰 이름 } AS
-- { VIEW 로 볼 내용 }
-- { WITH READ ONLY}

-- 1. 단일 테이블 뷰 (급여와 부서만 노출)
CREATE VIEW SingleTable AS
SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP;

SELECT * FROM SINGLETABLE;

-- 2. 조인 뷰 (부서명과 함께 사원 조회)

CREATE VIEW Joinview AS
SELECT e.EMPNO, e.ENAME, e.SAL, d.DNAME, d.LOC FROM EMP e, DEPT d;

SELECT * FROM JOINVIEW;

-- 3. 읽기 전용 강제

SELECT * FROM EMP;

CREATE VIEW READ_ONLY AS
SELECT DEPTNO, ENAME, JOB, SAL FROM EMP
WITH READ ONLY ;

SELECT * FROM READ_ONLY;